# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# Collect all Python files and dependencies
a = Analysis(
    ['app/main_prod.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app', 'app'),
        ('app/prompts', 'prompts'),
        ('pyproject.toml', '.'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.websockets',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'fastapi',
        'fastapi.openapi',
        'fastapi.openapi.docs',
        'pydantic',
        'pydantic_core',
        'pydantic_settings',
        'openai',
        'tenacity',
        'PIL',
        'PIL.Image',
        'multipart',
        'dotenv',
        'numpy',
        'simpleeval',
        'json',
        'asyncio',
        'logging',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'pandas',
        'scipy',
        'notebook',
        'jupyter',
        'IPython',
        'pytest',
        'ruff',
        'mypy',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='visualize-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    distpath='../dist',
    workpath='../build',
    specpath='.',
)